name: SOFTWAY HQ
title: HARDWAY
description: ITS MOTHERFUCKING HARDWAY HQ.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
  - title: Shop
    url: https://dorksidetees.com/collections/custom-designs
email: youremail@test.com
# See: https://disqus.com/
#disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
#formspree_form_id: formspree_form_id
