source "https://rubygems.org"

gem "kramdown"
gem "kramdown-parser-gfm"
gem "rouge"
gem "jekyll"
gem "jekyll-paginate"
gem "jekyll-paginate-content"
gem "json"
gem "github-pages", "~> 223", group: :jekyll_plugins