source "https://rubygems.org"

gem "kramdown", "~> 2.3.1"
gem "kramdown-parser-gfm", "~> 1.1.0"
gem "rouge", "~> 3.26.0"
#gem "jekyll", "~> 3.9.0"
gem "github-pages", "~> 223", group: :jekyll_plugins
gem "jekyll-paginate", "~> 1.1.0"
gem "jekyll-paginate-content"
gem "json"
